### ISSUE TITLE
Elevundersøkelsen

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/apps-backlog#4]
## Beskrivelse

Hvert år tar elever på 5. trinn (og noen trinn over) elevundersøkelsen (elevundersøkelse).

Svarene må anonymiseres før databehandling.

Lærerne må kunne se hvem som har levert undersøkelsen, og eventuelt selv starte undersøkelsen for elevene sine.

## Hensyn

- Studenten må autentisere seg med [Feide](https://www.feide.no/)
– Passordet er lite sikkert. Vi må analysere om pålogging får tilgang til meldingsboksen. Hvis ikke, hvordan beskytter vi dette
- Læreren aktiverer undersøkelsen for hver elev/klasse. Sannsynligvis en kilde til kompleksitet. Til vurdering: Kan første generasjon initieres av Udir?
– Læreren må ha oversikt over hvem som har gjennomført det. Sannsynligvis en kilde til kompleksitet. Til vurdering: Kan første generasjon være rapporter generert av Udir?
- Håndtering av undersøkelser som ikke er fullført innen en viss tid - bør de slettes, og i så fall hvordan / av hvem?
– Vi må vite hvilken skole/klasse elever er en del av. Hvordan gjør vi det? Assumption API fra UDIR/Feide
– Noen skoler bruker ikke Feide. Kan vi støtte dem? Forutsetning: NEI (de må opprette Feide-brukere)
- Noen brukere har kanskje ikke fnr./D-nr. Kan vi støtte dem? Forutsetning: NEI - i hvert fall ikke ved anonymisering
- Rekkefølgen på spørsmålene i undersøkelsen må være (pseudo)tilfeldig (slik at elevene ikke kan spore hvilke spørsmål andre elever i samme klasserom fyller ut). Forutsetning: Generer X standardiserte spørsmålsrekkefølger, og grupper elevene i samme antall grupper, og gi dem forskjellige spørsmålsrekkefølger.
– Noen spørsmål kan kreve innspill i andre formater enn det vi har etablert i Altinn 3 så langt. Forutsetning: Ingen av disse vil kreve nye dataformater, men snarere nye GUIer for å levere samme dataformat

![bilde](https://user-images.githubusercontent.com/13309071/128998984-da311935-5efa-4a7e-8232-7ed5f572db32.png)

### OAIDC-betraktning

Det er besluttet at bruk av ssn som ID og kartlegging til bruker i Altinn basert på det ikke er mulig. Ikke alle brukere har ssn i Feide og det er noe usikkerhet rundt datakvaliteten.

Så i Altinn skal vi kartlegge den eksterne identiteten til selvidentifiserte brukere i Altinn

– Er det noen begrensninger på Feide som OIDC-leverandør. Støtter de ISS, stat, nonce
- Hva er de spesifikke påstandsnavnene som brukes som skal brukes som ekstern identifikator
– Er det noe med Well know-endepunktet som gjør ting komplisert?
– Er det andre påstander som er aktuelle som bør oppbevares i Altinn-brikken
-

## Mulig løsning Feide
- [x] Altinn: Oppdater Altinn 3-støtte for å være og OIDC-klient Altinn/altinn-studio#6463
- [ ] Altinn: Oppdater Altinn 3 for å støtte kartlegging av eksternt konfigurert krav til en tilpasset ekstern identitet for selvidentifiserte brukere. Altinn/altinn-studio#6616
- [ ] Oppdater OIDC-støtte for FEIDE-leverandør som spesifikt. Se betraktninger.
- [ ] Konfigurer Feide som en juridisk ID-leverandør
- [ ] Legg til funksjonalitet i apper for å støtte en foretrukket autentiseringsleverandør
- [ ] Aff-funksjonalitet som forhindrer bruk av Altinn 3-token for å konvertere til Altinn 2 i noen tilfeller
- [ ] Logg ut funksjonalitet som går til feide

## Akseptkriterier

- [ ] UDIR definerer spørsmålene hvert år
- [ ] Skoler vil kanskje be om tilpassede spørsmål
- [ ] Elever logger inn gjennom FEIDE
- [ ] Undersøkelsen er ikke tilgjengelig i meldingsboksen / arkivet for brukeren

## Spesifikasjonsoppgaver

- [ ] Analyser hvordan vi kan bruke Feide som ID-leverandør for en gitt app. Skal appen kobles direkte til Feide eller skal Autentisering. Forutsetning er autentisering
- [ ] Analyser hva slags autentiseringsnivå Feide-bruker får. Er nivå 1 riktig. Teoretisk er det 1, men passordet er svakt
- [ ] Hvordan kan vi gjøre elementer skjult fra meldingsboksen. Innstillinger i appen?
- [ ] Hva slags støtte er nødvendig for å spore fremgang for en klasse. Noe i Altinn?
- [ ] Identifiser behovet for nye GUI-elementer (og muligens dataformater) for å gjøre input brukervennlig for denne nye brukergruppen
  - [ ] Identifiser om disse er generelt nyttige, eller om de skal være "engangsfunksjoner" for dette skjemaet

## Utviklingsoppgaver
- [x] Implementere støtte for Feide som ID-leverandør i Autentiseringskomponent
- [ ] Implementere mulig begrensning på meldingsbokselementer?
- [ ] Implementere nye GUI-elementer?
